name: Build

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: .NET Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0

    - name: Restoring
      run: dotnet restore -v normal

    - name: Building
      run: dotnet build -c Release --no-restore -v normal

    - name: Testing
      run: dotnet test -c Release --no-restore --no-build -v normal
