name: CI Workflow

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
    branches-ignore: [main]
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'
    branches-ignore: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
    - name: Git Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: .NET Setup
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10

    - name: Format
      run: dotnet format --verify-no-changes

  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
    - name: Git Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: .NET Setup
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10

    - name: Test
      run: dotnet test -c Release